# Dependencies
#markdown:         redcarpet
highlighter:      pygments
#pygments: true
#
gems: [jekyll-paginate, jekyll-gist]
# Permalinks




# Setup
title:            Amod Jog
tagline:          Amod Jog
description:      Research Fellow at <a href="https://martinos.org/lab/lcn" target="_blank">Laboratory of Computational Neuroimaging, MGH/HST Athinoula A. Martinos Center for Biomedical Imaging</a>
url:              /
baseurl:          /

author:
  name:           Amod Jog
  url:            www.asjog.github.io

paginate:         5



# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/asjog/asjog.github.io
# Google services
google_analytics: UA-91879051-1
