# Dependencies
#markdown:         redcarpet
highlighter:      rouge
#pygments: true
#
gems: [jekyll-paginate, jekyll-gist]
# Permalinks
permalink:        pretty
relative_permalinks: false


# Setup
title:            Amod Jog
tagline:          Amod Jog
description:      Research Fellow at <a href="https://martinos.org/lab/lcn" target="_blank">LCN at Martinos</a>
url:              www.iacl.jhu.edu/Amod
baseurl:          /

author:
  name:           Amod Jog
  url:            https://www.iacl.ece.jhu.edu/Amod

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/asjog/asjog.github.io
# Google services
google_analytics: UA-91879051-1
